window.BIRTHDAY_STRANDS_PUZZLE = {
  "title": "Birthday Strands",
  "recipient": "For your friend",
  "theme": "Favorite things",
  "winTitle": "Happy Birthday!",
  "winMessage": "You solved every level.",
  "puzzles": [
    {
      "label": "Level 1 - Film/TV + Literature",
      "theme": "Film, TV, and literature",
      "clip": {
        "src": "assets/x-popup.mp4",
        "durationMs": 3000,
        "cells": [
          [
            0,
            0
          ],
          [
            0,
            10
          ]
        ]
      },
      "grid": [
        "?OMENINRZA?",
        "BTILARCERAI",
        "RSRETPEEAKA",
        "EETTHECVHAH",
        "ALYEELAAONR",
        "KABBLTNDAAA",
        "FNOTITDIPYA",
        "ATANWODECID",
        "SOMEPREAPRU",
        "TNENTIDNDEJ",
        "ATTIFFANYS?"
      ],
      "answers": [
        {
          "word": "Atonement",
          "color": "#9f1239",
          "path": [
            [
              7,
              2
            ],
            [
              7,
              1
            ],
            [
              8,
              1
            ],
            [
              9,
              1
            ],
            [
              9,
              2
            ],
            [
              8,
              2
            ],
            [
              8,
              3
            ],
            [
              9,
              3
            ],
            [
              9,
              4
            ]
          ]
        },
        {
          "word": "Pride and Prejudice",
          "color": "#0d9488",
          "path": [
            [
              8,
              4
            ],
            [
              8,
              5
            ],
            [
              9,
              5
            ],
            [
              9,
              6
            ],
            [
              8,
              6
            ],
            [
              8,
              7
            ],
            [
              9,
              7
            ],
            [
              9,
              8
            ],
            [
              8,
              8
            ],
            [
              8,
              9
            ],
            [
              9,
              9
            ],
            [
              9,
              10
            ],
            [
              8,
              10
            ],
            [
              7,
              10
            ],
            [
              7,
              9
            ],
            [
              7,
              8
            ],
            [
              7,
              7
            ]
          ]
        },
        {
          "word": "Downton Abbey",
          "color": "#2563eb",
          "path": [
            [
              7,
              6
            ],
            [
              7,
              5
            ],
            [
              7,
              4
            ],
            [
              7,
              3
            ],
            [
              6,
              3
            ],
            [
              6,
              2
            ],
            [
              6,
              1
            ],
            [
              5,
              1
            ],
            [
              5,
              2
            ],
            [
              5,
              3
            ],
            [
              4,
              3
            ],
            [
              4,
              2
            ]
          ]
        },
        {
          "word": "Letters to Milena",
          "color": "#7c3aed",
          "path": [
            [
              4,
              1
            ],
            [
              3,
              1
            ],
            [
              3,
              2
            ],
            [
              3,
              3
            ],
            [
              2,
              3
            ],
            [
              2,
              2
            ],
            [
              2,
              1
            ],
            [
              1,
              1
            ],
            [
              0,
              1
            ],
            [
              0,
              2
            ],
            [
              1,
              2
            ],
            [
              1,
              3
            ],
            [
              0,
              3
            ],
            [
              0,
              4
            ],
            [
              1,
              4
            ]
          ]
        },
        {
          "word": "The Little Prince",
          "color": "#f59e0b",
          "path": [
            [
              2,
              4
            ],
            [
              3,
              4
            ],
            [
              4,
              4
            ],
            [
              5,
              4
            ],
            [
              6,
              4
            ],
            [
              6,
              5
            ],
            [
              5,
              5
            ],
            [
              4,
              5
            ],
            [
              3,
              5
            ],
            [
              2,
              5
            ],
            [
              1,
              5
            ],
            [
              0,
              5
            ],
            [
              0,
              6
            ],
            [
              1,
              6
            ],
            [
              2,
              6
            ]
          ]
        },
        {
          "word": "Candida",
          "color": "#0891b2",
          "path": [
            [
              3,
              6
            ],
            [
              4,
              6
            ],
            [
              5,
              6
            ],
            [
              6,
              6
            ],
            [
              6,
              7
            ],
            [
              5,
              7
            ],
            [
              4,
              7
            ]
          ]
        },
        {
          "word": "Veer Zaara",
          "color": "#be123c",
          "path": [
            [
              3,
              7
            ],
            [
              2,
              7
            ],
            [
              1,
              7
            ],
            [
              0,
              7
            ],
            [
              0,
              8
            ],
            [
              0,
              9
            ],
            [
              1,
              9
            ],
            [
              1,
              8
            ],
            [
              2,
              8
            ]
          ]
        },
        {
          "word": "Kaho Naa Pyaar Hai",
          "color": "#db2777",
          "path": [
            [
              2,
              9
            ],
            [
              3,
              9
            ],
            [
              3,
              8
            ],
            [
              4,
              8
            ],
            [
              4,
              9
            ],
            [
              5,
              9
            ],
            [
              5,
              8
            ],
            [
              6,
              8
            ],
            [
              6,
              9
            ],
            [
              6,
              10
            ],
            [
              5,
              10
            ],
            [
              4,
              10
            ],
            [
              3,
              10
            ],
            [
              2,
              10
            ],
            [
              1,
              10
            ]
          ]
        },
        {
          "word": "Breakfast At Tiffinays",
          "color": "#f97316",
          "path": [
            [
              1,
              0
            ],
            [
              2,
              0
            ],
            [
              3,
              0
            ],
            [
              4,
              0
            ],
            [
              5,
              0
            ],
            [
              6,
              0
            ],
            [
              7,
              0
            ],
            [
              8,
              0
            ],
            [
              9,
              0
            ],
            [
              10,
              0
            ],
            [
              10,
              1
            ],
            [
              10,
              2
            ],
            [
              10,
              3
            ],
            [
              10,
              4
            ],
            [
              10,
              5
            ],
            [
              10,
              6
            ],
            [
              10,
              7
            ],
            [
              10,
              8
            ],
            [
              10,
              9
            ],
            [
              10,
              10
            ]
          ],
          "kind": "spangram"
        }
      ]
    },
    {
      "label": "Level 2 - Other Favorites",
      "theme": "Other favorites",
      "grid": [
        "SRSNOCAERUQ",
        "HENOOCRLRIS",
        "TSAWPEAOWER",
        "AEYINASLFGR",
        "SFGNDLREDYE",
        "MOTHGIOLICL",
        "RONIREILHCO",
        "HSGSLENBEDU",
        "MUESAVENALA",
        "SDEREDNSSAD"
      ],
      "answers": [
        {
          "word": "Snow Peas and Green Beans salad",
          "color": "#16a34a",
          "path": [
            [
              0,
              2
            ],
            [
              1,
              2
            ],
            [
              1,
              3
            ],
            [
              2,
              3
            ],
            [
              2,
              4
            ],
            [
              2,
              5
            ],
            [
              2,
              6
            ],
            [
              3,
              6
            ],
            [
              3,
              5
            ],
            [
              3,
              4
            ],
            [
              4,
              4
            ],
            [
              5,
              4
            ],
            [
              6,
              4
            ],
            [
              6,
              5
            ],
            [
              7,
              5
            ],
            [
              7,
              6
            ],
            [
              7,
              7
            ],
            [
              7,
              8
            ],
            [
              8,
              8
            ],
            [
              8,
              7
            ],
            [
              9,
              7
            ],
            [
              9,
              8
            ],
            [
              9,
              9
            ],
            [
              8,
              9
            ],
            [
              8,
              10
            ],
            [
              9,
              10
            ]
          ],
          "kind": "spangram"
        },
        {
          "word": "Saying Things",
          "color": "#6d28d9",
          "path": [
            [
              2,
              1
            ],
            [
              2,
              2
            ],
            [
              3,
              2
            ],
            [
              3,
              3
            ],
            [
              4,
              3
            ],
            [
              4,
              2
            ],
            [
              5,
              2
            ],
            [
              5,
              3
            ],
            [
              6,
              3
            ],
            [
              6,
              2
            ],
            [
              7,
              2
            ],
            [
              7,
              3
            ]
          ]
        },
        {
          "word": "Lavender Seeds",
          "color": "#8b5cf6",
          "path": [
            [
              7,
              4
            ],
            [
              8,
              4
            ],
            [
              8,
              5
            ],
            [
              8,
              6
            ],
            [
              9,
              6
            ],
            [
              9,
              5
            ],
            [
              9,
              4
            ],
            [
              9,
              3
            ],
            [
              8,
              3
            ],
            [
              8,
              2
            ],
            [
              9,
              2
            ],
            [
              9,
              1
            ],
            [
              9,
              0
            ]
          ]
        },
        {
          "word": "Mushrooms",
          "color": "#92400e",
          "path": [
            [
              8,
              0
            ],
            [
              8,
              1
            ],
            [
              7,
              1
            ],
            [
              7,
              0
            ],
            [
              6,
              0
            ],
            [
              6,
              1
            ],
            [
              5,
              1
            ],
            [
              5,
              0
            ],
            [
              4,
              0
            ]
          ]
        },
        {
          "word": "Feathers",
          "color": "#a16207",
          "path": [
            [
              4,
              1
            ],
            [
              3,
              1
            ],
            [
              3,
              0
            ],
            [
              2,
              0
            ],
            [
              1,
              0
            ],
            [
              1,
              1
            ],
            [
              0,
              1
            ],
            [
              0,
              0
            ]
          ]
        },
        {
          "word": "Grey Cloud",
          "color": "#64748b",
          "path": [
            [
              3,
              9
            ],
            [
              3,
              10
            ],
            [
              4,
              10
            ],
            [
              4,
              9
            ],
            [
              5,
              9
            ],
            [
              5,
              10
            ],
            [
              6,
              10
            ],
            [
              7,
              10
            ],
            [
              7,
              9
            ]
          ]
        },
        {
          "word": "Chilli Oil",
          "color": "#ea580c",
          "path": [
            [
              6,
              9
            ],
            [
              6,
              8
            ],
            [
              5,
              8
            ],
            [
              5,
              7
            ],
            [
              6,
              7
            ],
            [
              6,
              6
            ],
            [
              5,
              6
            ],
            [
              5,
              5
            ],
            [
              4,
              5
            ]
          ]
        },
        {
          "word": "Red Flower",
          "color": "#dc2626",
          "path": [
            [
              4,
              6
            ],
            [
              4,
              7
            ],
            [
              4,
              8
            ],
            [
              3,
              8
            ],
            [
              3,
              7
            ],
            [
              2,
              7
            ],
            [
              2,
              8
            ],
            [
              2,
              9
            ],
            [
              2,
              10
            ]
          ]
        },
        {
          "word": "Squirrel",
          "color": "#b45309",
          "path": [
            [
              1,
              10
            ],
            [
              0,
              10
            ],
            [
              0,
              9
            ],
            [
              1,
              9
            ],
            [
              1,
              8
            ],
            [
              0,
              8
            ],
            [
              0,
              7
            ],
            [
              1,
              7
            ]
          ]
        },
        {
          "word": "Raccoon",
          "color": "#374151",
          "path": [
            [
              1,
              6
            ],
            [
              0,
              6
            ],
            [
              0,
              5
            ],
            [
              1,
              5
            ],
            [
              1,
              4
            ],
            [
              0,
              4
            ],
            [
              0,
              3
            ]
          ]
        }
      ]
    }
  ]
};
